name: flutter_todolist
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # gradient_app_bar: ^0.1.3
  # https://github.com/joostlek/GradientAppBar/issues/23
  gradient_app_bar:
    git:
      url: https://github.com/TinyProgrammers/GradientAppBar.git
  flutter_slidable: "^0.6.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/

  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
